/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rectangle;

import org.junit.Test;
import static org.junit.Assert.*;

public class RectangleTest {

    @Test
    public void testArea() {
        Rectangle rectangle = buildRectangle(3,2);
        assert rectangle.area() == 6;
    }


    @Test
    public void testPerimeter() {
        Rectangle rectangle = buildRectangle(3, 2);
        assert rectangle.perimeter() == 10;
    }

    private Rectangle buildRectangle(double length, double width) {
        return new Rectangle(length, width);
    }
}
