/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rectangle;

public class Rectangle {
    private double length;
    private double width;

    public Rectangle(double length, double width) {
        this.length = length;
        this.width = width;
    }

    public double area() {
        return length * width;
    }

    public double perimeter() {
        return (width + length) * 2;
    }
}
