/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rectangle;

public class Rectangle {
    private double length;
    private double shortside;

    public Rectangle(double length, double width) {
        this.length = length;
        this.shortside = width;
    }

    public double area() {
        return length * shortside;
    }

    public double perimeter() {
        return (shortside + length) * 2;
    }
}
